### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by adamretter**

### CODE REVIEW

**Comment by cowtowncoder** [comment]
First fix makes sense.

But as to second part: Latin-1 is not actually supported encoding at this point; decoder assumes UTF-8 (or compatible, so 7-bit ASCII is fine). Adding support would probably be doable, but for now attempts to feed Latin-1 would lead to either corruption, or decoding error, for chacters in `0x80` - `0xFF` range.
(ditto for other ISO-8859-x encodings).

**Comment by cowtowncoder** [comment]
Manually merged fix for hex-char-entity for attributes with byte-buffer fix (needed to also handle different base value).

**Comment by adamretter** [comment]
Thanks any hints on what I should do in the decoder for Latin? I took a look but it wasn't obvious to me.

The Latin attempt solved my problem, I admit it was a hack though and the XML I have to parse is actually all valid Ascii.

**Comment by cowtowncoder** [comment]
@adamretter Problem is just that UTF-8 decoder works fine with 7-bit ascii (it being subset). But for 1-byte fixed-size encodings things are bit different. It has been a while, but I suspect that it just might be possible to change decode tables to make it happen... there's 256-byte (or int) table used for determining what to do based on initial byte value, and one of values indicates "multi-byte UTF-8". Changing that just might allow easy and efficient (enough) decoding.

I'll see if I can dig more info to refresh my memory here.

**Comment by cowtowncoder** [comment]
Hmmmmh. I wonder if it might actually... "just work". :)

I think I'll try writing a simple test with some Latin-1 characters and see if things would work.
Seems plausible.

**Comment by cowtowncoder** [comment]
Interesting. So, it almost "just works", but not quite. Problem being that although encoding declaration is detected from xml declaration and even applied to configuration, decoding tables have been already initialized. This becomes blocking parser uses separate bootstrapper which handles declaration and can determine actual encoding, using all sources. Not so for async which does not use bootstrapper. Ideally it probably should, as that makes sense from handling perspective... but that'd be bigger refactoring.

So what I can do instead, in meantime, is to update configuration and decoding table.
Right now that leads to another problem with symbol table updates (since symbol tables are, by necessity, encoding specific). But I hope I can work around that....

**Comment by cowtowncoder** [comment]
Solving Latin-1 for reals, will create separate issues.

**Comment by adamretter** [comment]
Thank you again @cowtowncoder

**Pull request closed without merging**
